---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - nginx.dustinke.me
  resources:
  - virtualservermanagers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nginx.dustinke.me
  resources:
  - virtualservermanagers/finalizers
  verbs:
  - update
- apiGroups:
  - nginx.dustinke.me
  resources:
  - virtualservermanagers/status
  verbs:
  - get
  - patch
  - update
