# permissions for end users to view virtualservermanagers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: virtualservermanager-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: virtualserver-manager
    app.kubernetes.io/part-of: virtualserver-manager
    app.kubernetes.io/managed-by: kustomize
  name: virtualservermanager-viewer-role
rules:
- apiGroups:
  - nginx.dustinke.me
  resources:
  - virtualservermanagers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nginx.dustinke.me
  resources:
  - virtualservermanagers/status
  verbs:
  - get
